# Generated by Django 3.1.2 on 2020-12-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotask',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
